import type { Metadata } from "next";
import { Livvic } from "next/font/google";
import Layout from "@/components/Layout";
import "./globals.css";
const livvic = Livvic({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${livvic.className} antialiased bg-background`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
